### ISSUE TITLE
Commands for windows

### ISSUE THREAD

**Issue by Srivatsaaa** [ehooo/django_mqtt#13]
Thanks for your reference @ehooo but I facing issues for commands in windows because you only given UNIX commands here but I needed Windows Commands

**Comment by ehooo** [comment]
Hi @Srivatsaaa 
What commands you talking about? the[INSTALL.sh](test_web/INSTALL.sh) and [CONFIGURE.sh](test_web/CONFIGURE.sh) ? thit are only for test propose.

I don't have any Windows for test, but i'm not sure if is possible to do all in shell mode, as Linux do.

Maybe you could create a docker image for use it on Windows.

**Comment by Srivatsaaa** [comment]
@ehooo Thanks you sir,I will check it and come back to you.

**Comment by ehooo** [comment]
@Srivatsaaa any update?
