### ISSUE TITLE
Get Auth form Settings1

### ISSUE THREAD

**Issue by ehooo** [ehooo/django_mqtt#2]
On Mosquitto auth get the user from the settings

**Comment by wharpreet** [comment]
Hey,
First of all thanks for this plugin.
Any pointers on how to set ACL and users. Tables and schema is all set, but do we need to add users and ACl manually?
If yes then which all tables need to be populated for this work properly (for publishing)
Using this plugin I am able to subscribe (with my users in django/mysql)

PS: Didn't know where else to post this question, hence posting it here.
Thanks

**Comment by ehooo** [comment]
Hi @wharpreet 
I want to improve this project and refactor a lot of thing.

Now:
 - the auth mechanism allow all the django active user
 - If you have some ACL it will applied to all users

I want to improve this plugin and use all the parameters that the "mosquitto-auth-plug" have.


This topic is for change the User class and use it from: https://docs.djangoproject.com/en/1.11/ref/settings/#auth-user-model

Regards

**Comment by ehooo** [comment]
@wharpreet  i closed this issue but please feel free to open new one if you have any question.
