### ISSUE TITLE
Secure confs ADD

### ISSUE THREAD

**Issue by ccaiuss** [ehooo/django_mqtt#21]
I can't add the certificates. I encountered two errors

Select a valid choice. VerifyMode.CERT_REQUIRED is not one of the available choices.
Select a valid choice. _SSLMethod.PROTOCOL_TLSv1 is not one of the available choices.

**Comment by ehooo** [comment]
Hi @ccaiuss 
Could you tell me more information aobut your system?
What python version are you running?
Could you paste you pip freeze?

Regards

**Comment by ccaiuss** [comment]
Ubuntu 20.10

sgiref==3.3.1
autopep8==1.5.6
certifi==2020.12.5
chardet==4.0.0
dj-database-url==0.5.0
Django==3.1.7
django-channels==0.7.0
django-enum-choices==2.1.3
django-enumchoicefield==2.0.0
djangorestframework==3.12.2
gunicorn==20.0.4
idna==2.10
oauthlib==3.1.0
paho-mqtt==1.5.1
pycodestyle==2.7.0
python-decouple==3.4
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
six==1.15.0
sqlparse==0.4.1
toml==0.10.2
Unipath==1.1
urllib3==1.26.4
whitenoise==5.2.0

**Comment by ehooo** [comment]
@ccaiuss coulld you share the project in order to test the MQTT configuration and test the root cause?

**Comment by ccaiuss** [comment]
[iotapp.zip](https://github.com/ehooo/django_mqtt/files/6173472/iotapp.zip)

- can't add server from this link: http://localhost:8080/admin/publisher/secureconf/add/
- Wildcard and dollar checkboxes do not work on this page: http://localhost:8080/admin/django_mqtt/topic/add/

**Comment by ehooo** [comment]
@ccaiuss related to wildcard and dollar checkboxes must be autocompleted

Could you tellme what topics are you test?
