### ISSUE TITLE
GPL Licence question

### ISSUE THREAD

**Issue by vdboor** [ehooo/django_mqtt#29]
I see this popular project uses the GPL license. Often in Python land I've learned this isn't always intentional, and sometimes a mistake.

Is your intention that any project that uses this library should be open sourced as GPL?
Basically, an commercial usage of this library in a private project is now forbidden and risks lawsuit.

If that wasn't your intention, could you please change the license to LGPL? (or BSD). Using the LGPL would still enforce authors to contribute any changes to this library, but no longer enforces any project that uses this library to become GPL too.

**Comment by ehooo** [comment]
Hello @vdboor I just change the licence.
Kind regards
