### ISSUE TITLE
Why is Django limited <=1.9.1 ?

### ISSUE THREAD

**Issue by royemmerich** [ehooo/django_mqtt#5]
I'm running Django 1.11.5 and would like to connect to a MQTT broker using your library. I see in the `requirements.txt` you've limited the Django version to v1.9.1. Is there a specific reason for this?

https://github.com/ehooo/django_mqtt/blob/d61bdc970a932b2ccbbb86eee7d6291617f9a736/requirements.txt#L1

**Comment by ehooo** [comment]
It was the last version when i started this project
