### ISSUE TITLE
[Feature Request] usage documentation

### ISSUE THREAD

**Issue by royemmerich** [ehooo/django_mqtt#6]
It would be great if you could provide a few clearer examples of how you use the MQTT connection in a Django app.

I'm specifically wanting to do the following two tasks but am unsure how:

* subscribe to a specific MQTT topic and keep a text field or many text fields in my HTML page up to date when new data comes in.
* publish data to a topic/various topics upon saving a form

Many thanks in advance.

**Comment by ehooo** [comment]
Hi @royemmerich 
Sorry for delay reply you.

I hope the new documentation is more clear about the steps to create a new "mqtt data" and update to remote server.

If you want realtime update, I thing that you should choose WebSockets interface.

However i think would be cool create a new manager for update one specific data; so i will do it when i have time for it.

Thanks for your feedback.
Please feel free to tell me any question that you have.
